name: Sum Issues by Category

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: read

jobs:
  sum-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Download external script
        run: |
          curl -o sum-issues-by-category.js https://raw.githubusercontent.com/3ee-Games/github-actions/refs/heads/main/scripts/sum-issues-by-category.js

      - name: Run Sum Issues by Category script
        run: |
          echo "Running issue summation script by category"
          node sum-issues-by-category.js

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ./public/category-sum.json
          git commit -m "Update category-sum.json"
          git push