name: Sum Issues by Category

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: read

jobs:
  sum-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Sum Issues by Category
        run: |
          echo "Running issue summation script by category"
          cat << 'EOF' > script.js
          const fs = require('fs');
          const path = './public';

          const categories = {
              games: ['gorgon-issue-tracker.yml', 'hoa-issue-tracker.yml', 'spin-issue-tracker.yml'],
              apis: ['api-issue-tracker.yml'],
              web: ['website-issue-tracker.yml']
          };

          const sums = {
              games: { resolved_bugs: 0, resolved_documentation: 0, resolved_enhancements: 0 },
              apis: { resolved_bugs: 0, resolved_documentation: 0, resolved_enhancements: 0 },
              web: { resolved_bugs: 0, resolved_documentation: 0, resolved_enhancements: 0 }
          };

          // Summarize issues per category
          fs.readdirSync(path).forEach(file => {
              if (file.endsWith('.json')) {
                  const data = JSON.parse(fs.readFileSync(`${path}/${file}`, 'utf-8'));

                  for (const [category, files] of Object.entries(categories)) {
                      if (files.includes(file)) {
                          sums[category].resolved_bugs += data.resolved_bugs || 0;
                          sums[category].resolved_documentation += data.resolved_documentation || 0;
                          sums[category].resolved_enhancements += data.resolved_enhancements || 0;
                      }
                  }
              }
          });

          // Write the category sums to a new JSON file
          fs.writeFileSync(`${path}/category-sums.json`, JSON.stringify(sums, null, 2));

          console.log('Generated category-sums.json:', sums);
          EOF

          node script.js

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ./public/category-sum.json
          git commit -m "Update category-sum.json"
          git push
