name: Sum Issues by Category

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: read

jobs:
  sum-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Sum Issues by Category script
        run: |
          echo "Running issue summation script by category"
          node ./scripts/sum-issues-by-category.js

      - name: Check Git Status
        run: |
          git status
          git diff

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          add: ./public/category-sum.json
          message: "Update category-sum.json"
          push: true