name: Sum Issues

on:
  schedule:
    - cron: '0 6 * * *' #6am
  workflow_dispatch:

permissions:
  contents: write
  issues: read

jobs:
  sum-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Sum Issues from JSON Files
        run: |
          echo "Running issue summation script"
          cat << 'EOF' > script.js
          const fs = require('fs');
          const path = './public';
          let totalResolvedBugs = 0;
          let totalResolvedDocs = 0;
          let totalResolvedEnhancements = 0;

          fs.readdirSync(path).forEach(file => {
              if (file.endsWith('.json')) {
                  const data = JSON.parse(fs.readFileSync(`${path}/${file}`, 'utf-8'));
                  totalResolvedBugs += data.resolved_bugs || 0;
                  totalResolvedDocs += data.resolved_documentation || 0;
                  totalResolvedEnhancements += data.resolved_enhancements || 0;
              }
          });

          const output = {
              resolved_bugs: totalResolvedBugs,
              resolved_documentation: totalResolvedDocs,
              resolved_enhancements: totalResolvedEnhancements,
          };

          fs.writeFileSync('./public/all-issues-count.json', JSON.stringify(output, null, 2));
          console.log('Generated all-issues-count.json:', output);
          EOF

          node script.js

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ./public/all-issues-count.json
          git commit -m "Update all-issues-count.json"
          git push