name: Sum Issues

on:
  schedule:
    - cron: '0 6 * * *' #6 AM
  workflow_dispatch:

jobs:
  sum-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Sum Issues from JSON Files
        run: |
          node <<EOF
          const fs = require('fs');
          const path = require('path');

          const publicDir = path.resolve('./public'); // Ensure proper path
          const outputFile = path.resolve(publicDir, 'all-issues-count.json');

          let totalResolvedBugs = 0;
          let totalResolvedDocs = 0;
          let totalResolvedEnhancements = 0;

          // Check if the public directory exists
          if (!fs.existsSync(publicDir)) {
              throw new Error(`Directory not found: ${publicDir}`);
          }

          // Read and process each JSON file in the directory
          fs.readdirSync(publicDir).forEach(file => {
              const filePath = path.join(publicDir, file); // Properly construct file path

              // Only process JSON files
              if (file.endsWith('.json')) {
                  try {
                      const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
                      totalResolvedBugs += data.resolved_bugs || 0;
                      totalResolvedDocs += data.resolved_documentation || 0;
                      totalResolvedEnhancements += data.resolved_enhancements || 0;
                  } catch (err) {
                      console.error(`Error processing file: ${filePath}`, err.message);
                  }
              }
          });

          // Write the summarized data to the output file
          const output = {
              resolved_bugs: totalResolvedBugs,
              resolved_documentation: totalResolvedDocs,
              resolved_enhancements: totalResolvedEnhancements,
          };

          fs.writeFileSync(outputFile, JSON.stringify(output, null, 2));
          console.log('Generated all-issues-count.json:', output);
          EOF

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ./public/all-issues-count.json
          git commit -m "Update all-issues-count.json"
          git push
