name: Sum JSON Issues

on:
  schedule:
    - cron: '0 6 * * *' #6 AM
  workflow_dispatch:

permissions:
  contents: write
  issues: read
    
jobs:
  sum-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install fs

      - name: Sum Issues from JSON Files
        run: |
          node <<EOF
          const fs = require('fs');
          const path = './public';
          let totalResolvedBugs = 0;
          let totalResolvedDocs = 0;
          let totalResolvedEnhancements = 0;

          // Check if the directory exists
          if (!fs.existsSync(path)) {
              throw new Error(`Directory not found: ${path}`);
          }

          fs.readdirSync(path).forEach(file => {
              const filePath = `${path}/${file}`; // Full file path
              
              // Only process JSON files
              if (file.endsWith('.json')) {
                  try {
                      const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
                      totalResolvedBugs += data.resolved_bugs || 0;
                      totalResolvedDocs += data.resolved_documentation || 0;
                      totalResolvedEnhancements += data.resolved_enhancements || 0;
                  } catch (err) {
                      console.error(`Error processing file: ${filePath}`, err);
                  }
              }
          });

          const output = {
              resolved_bugs: totalResolvedBugs,
              resolved_documentation: totalResolvedDocs,
              resolved_enhancements: totalResolvedEnhancements,
          };

          fs.writeFileSync('./public/all_issues_count.json', JSON.stringify(output, null, 2));
          console.log('Generated all_issues_count.json:', output);
          EOF

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add ./public/all_issues_count.json
          git commit -m "Update all_issues_count.json [CI]"
          git push
