name: Track Resolved Bugs

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write
  issues: read

jobs:
  track-bugs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Fetch All Closed Bug Issues (GraphQL)
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          OWNER="3ee-Games"
          REPO="hoa-simulator"
          LABEL="bug"
          TOTAL_BUGS=0
          
          # Create temporary GraphQL query file to fetch closed issues
          cat <<EOF > query.json
          {
            "query": "query {
              repository(owner: \"3ee-Games\", name: \"hoa-simulator\") {
                issues(first: 100, labels: [\"bug\"], states: CLOSED) {
                  totalCount
                }
              }
            }"
          }
          EOF

          RESPONSE=$(curl -s -X POST -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d @query.json https://api.github.com/graphql)

          # Log the entire response for debugging purposes
          echo "DEBUG: Full Response: $RESPONSE"

          # Get the total count of closed bug issues
          TOTAL_BUGS=$(echo $RESPONSE | jq '.data.repository.issues.totalCount')

          # Check if total bugs is null and log error if so
          if [ "$TOTAL_BUGS" == "null" ]; then
            echo "ERROR: Total bugs count is null!"
          else
            echo "DEBUG: Total bugs resolved = $TOTAL_BUGS"
          fi

          mkdir -p public
          echo "{\"resolved_bugs\": $TOTAL_BUGS}" > public/bug-count.json

      - name: Check Git Status
        run: |
          git status
          git diff

      - name: Commit and Push Bug Count
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/bug-count.json
          git commit -m "Update bug count" || echo "No changes to commit"
          git push
