name: Track Resolved Bugs

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Manual trigger

jobs:
  track-bugs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch All Closed Bug Issues (Paginated)
        run: |
          PAGE=1
          TOTAL_BUGS=0
          
          while :; do
            RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "https://api.github.com/repos/3ee-Games/3ee-api/issues?labels=bug&state=closed&page=$PAGE&per_page=2")
            
            BUG_COUNT=$(echo $RESPONSE | jq '. | length')
            
            if [ $BUG_COUNT -eq 0 ]; then
              break
            fi
            
            TOTAL_BUGS=$((TOTAL_BUGS + BUG_COUNT))
            PAGE=$((PAGE + 1))
          done
          
          echo "{\"resolved_bugs\": $TOTAL_BUGS}" > public/bug-count.json

      - name: Commit and Push Bug Count
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/bug-count.json
          git commit -m "Update bug count" || echo "No changes to commit"
          git push
